apiVersion: apps/v1
kind: StatefulSet
metadata:

  name: phpcli
  labels:
    app: phpcli
spec:
  serviceName: phpcli
  replicas: 1
  selector:
    matchLabels:
      app: phpcli
  template:
    metadata:
      labels:
        app: phpcli
    spec:
      containers:
        - name: phpcli
          image: foxiswho/php-alpine:php73
          imagePullPolicy: IfNotPresent
#          resources:
#            limits:
#              cpu: 450m
#              memory: 4000Mi
#            requests:
#              cpu: 400m
#              memory: 4000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
          command: ["php","/wwwroot/demo/demo.php"]
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: vol-data
              mountPath: /wwwroot
            - name: vm-log-default
              mountPath: /var/log/www/default
      volumes:
        - name: vol-data
          hostPath:
              path: /www/k8s/knprmelk/nginx/wwwroot
              type: Directory
        - name: vm-log-default
          emptyDir: { }
