

apiVersion: v1
kind: Service
metadata:

  name: phpcli
  labels:
    app: phpcli
spec:
#  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
#      nodePort: 39000
  selector:
    app: phpcli